Register integration
wolox-training/bj-rails pull request #7
Opened 2019-01-11 00:45 UTC by BJordi

## Summary

- Added apisauce
- Added api configuration
- Added service to sign up users.
- Added sign up service to the onSubmit method in the login form.

2019-01-11 00:53 UTC, FrankIglesias requested changes

2019-01-11 00:53 UTC, FrankIglesias commented on src/views/Login.vue
> +      debugger
remove the debugger

2019-01-11 00:54 UTC, BJordi commented on src/views/Login.vue
> +      debugger
Haha, my bad! :sweat_smile:

2019-01-11 17:48 UTC, FrankIglesias approved these changes

2019-01-16 02:28 UTC, FrankIglesias approved these changes

2019-01-16 16:16 UTC, merged